# Generated by Django 4.2.3 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/about/')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=7000)),
            ],
        ),
        migrations.CreateModel(
            name='Aqili_gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('job_nmae', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='midea/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='midea/images/')),
                ('number_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistika_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=7000)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/team/')),
                ('full_name', models.CharField(max_length=256)),
                ('job_name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/product/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=7000)),
                ('images_statis', models.ImageField(upload_to='midea/statis_product/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzb.category_product')),
            ],
        ),
    ]
