# Generated by Django 4.2.3 on 2023-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzb', '0002_category_certificat_certificats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/team/')),
                ('full_name', models.CharField(max_length=256)),
                ('job_name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=500)),
                ('videofile', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
