# Generated by Django 4.2.3 on 2023-08-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=80)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/team/')),
                ('full_name', models.CharField(max_length=256)),
                ('job_name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=500)),
                ('videofile', models.CharField(max_length=600, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
