# Generated by Django 4.2.3 on 2023-07-31 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('images', models.ImageField(upload_to='midea/images/')),
                ('number_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/product/')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=7000)),
                ('images_statis', models.ImageField(upload_to='midea/statis_product/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eng.category_product')),
            ],
        ),
    ]
