# Generated by Django 4.2.3 on 2023-07-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistika_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(max_length=7000)),
            ],
        ),
    ]
