# Generated by Django 4.2.3 on 2023-07-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0002_statistika_statistika_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/about/')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=7000)),
            ],
        ),
    ]
