# Generated by Django 4.2.3 on 2023-07-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0003_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_one',
        ),
    ]
