# Generated by Django 4.2.3 on 2023-07-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0005_aqili_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/team/')),
                ('full_name', models.CharField(max_length=256)),
                ('job_name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
