# Generated by Django 4.2.3 on 2023-07-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0007_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='midea/certificat/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eng.category_certificat')),
            ],
        ),
    ]
