# Generated by Django 4.2.3 on 2023-07-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0008_category_certificat_certificat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificat',
            new_name='Certificats',
        ),
    ]
