# Generated by Django 4.2.3 on 2023-08-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midea/team/')),
                ('full_name', models.CharField(max_length=256)),
                ('job_name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
