# Generated by Django 4.2.3 on 2023-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0013_alter_factory_about_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory_about',
            name='videofile',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
